# Generated by Django 4.2.4 on 2023-08-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiqAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerPlantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
                ('plant_state', models.CharField(max_length=2)),
                ('annual_net_generation', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=2)),
                ('state_annual_net_generation', models.IntegerField()),
            ],
        ),
    ]
