# Generated by Django 4.2.4 on 2023-08-11 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiqAPI', '0003_remove_powerplantmodel_percentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
